server:
  port: 8080
frontend:
  login-page: http://109.196.102.221/habit-tracker/auth/login/
  main-page: http://109.196.102.221/habit-tracker/main/
spring:
  application:
    name: HabitTracker
  datasource:
    url: jdbc:postgresql://109.196.102.221:5436/postgres
    username: postgres
    password: bJnr4cCcxN19
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
